spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${TICKETERA_DB_URL:jdbc:postgresql://localhost:5433/ticketera_db}
    username: ${TICKETERA_DB_USERNAME:user_ticketera}
    password: ${TICKETERA_DB_PASSWORD:pass_ticketera}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}

server:
  port: ${SERVER_PORT:8081}