-- ============================================================================
-- Ticketera - Inicializacion del esquema PostgreSQL
-- ============================================================================
-- Este script replica EXACTAMENTE el esquema que Hibernate genera a partir de
-- las entidades JPA (CityEntity, EventEntity, TicketEntity). Se ejecuta una
-- sola vez: cuando el contenedor de PostgreSQL arranca con el volumen de datos
-- VACIO (directorio /docker-entrypoint-initdb.d). El perfil prod usa
-- ddl-auto: validate, que solo valida contra las entidades, no crea tablas;
-- por eso una base nueva necesita este esquema para poder arrancar.
-- ============================================================================

CREATE TABLE IF NOT EXISTS cities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    city_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    venue varchar(255) NOT NULL,
    capacity integer NOT NULL,
    available_tickets integer NOT NULL,
    artist varchar(255),
    event_date timestamp(6) without time zone,
    event_time varchar(10),
    price double precision,
    image_url varchar(255),
    featured boolean NOT NULL,
    status varchar(20)
);

CREATE TABLE IF NOT EXISTS tickets (
    id varchar(36) PRIMARY KEY,
    event_id bigint NOT NULL,
    customer_name varchar(255),
    customer_email varchar(255),
    order_id varchar(36),
    unit_price double precision,
    total_amount double precision,
    status varchar(20),
    created_at timestamp(6) without time zone
);

-- Datos de prueba (solo se insertan en la primera ejecucion, cuando el volumen de datos está vacío)
INSERT INTO cities (code, name) VALUES 
('LIM', 'Lima'),
('BOG', 'Bogotá'),
('MAD', 'Madrid');

INSERT INTO events (code, city_id, name, venue, capacity, available_tickets, artist, event_date, event_time, price, image_url, featured, status) VALUES 
('evt-jazz-001', 1, 'Jazz Night', 'Gran Teatro Lima', 500, 500, 'Miles Davis Quartet', '2026-12-15T20:00:00', '20:00', 25000.0, '/images/jazz.webp', true, 'ON_SALE'),
('evt-rock-002', 2, 'Rock Fest', 'Estadio Nacional', 5000, 3800, 'AC/DC', '2026-12-20T19:00:00', '19:00', 55000.0, '/images/rock.webp', false, 'SCHEDULED'),
('evt-opera-003', 3, 'La Traviata', 'Teatro Real Madrid', 800, 0, 'Placido Domingo', '2027-02-14T19:30:00', '19:30', 120000.0, '/images/opera.webp', true, 'SOLD_OUT'),
('evt-fest-004', 2, 'Bogota Music Festival', 'Parque Simon Bolivar', 10000, 10000, 'Various Artists', '2026-11-30T18:00:00', '18:00', 80000.0, '/images/fest.webp', false, 'SCHEDULED');