-- ============================================================================
-- Ticketera - Inicializacion del esquema PostgreSQL
-- ============================================================================
-- Este script replica EXACTAMENTE el esquema que Hibernate genera a partir de
-- las entidades JPA (CityEntity, EventEntity, TicketEntity, UserEntity). Se
-- ejecuta una sola vez: cuando el contenedor de PostgreSQL arranca con el
-- volumen de datos VACIO (directorio /docker-entrypoint-initdb.d). El perfil
-- prod usa ddl-auto: validate, que solo valida contra las entidades, no crea
-- tablas; por eso una base nueva necesita este esquema para poder arrancar.
-- ============================================================================

CREATE TABLE IF NOT EXISTS cities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    city_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    venue varchar(255) NOT NULL,
    capacity integer NOT NULL,
    available_tickets integer NOT NULL,
    artist varchar(255),
    event_date timestamp(6) without time zone,
    event_time varchar(10),
    price double precision,
    image_url varchar(255),
    featured boolean NOT NULL,
    status varchar(20)
);

CREATE TABLE IF NOT EXISTS tickets (
    id varchar(36) PRIMARY KEY,
    event_id bigint NOT NULL,
    customer_name varchar(255),
    customer_email varchar(255),
    order_id varchar(36),
    unit_price double precision,
    total_amount double precision,
    status varchar(20),
    user_id bigint,
    created_at timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(120) NOT NULL UNIQUE,
    full_name varchar(160) NOT NULL,
    encoded_password varchar(255) NOT NULL,
    role varchar(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

-- Datos semilla (solo se insertan en la primera ejecución, cuando el volumen de datos está vacío)
-- Ciudades de Chile
INSERT INTO cities (code, name) VALUES 
('SCL', 'Santiago'),
('VAP', 'Valparaíso'),
('VDA', 'Valdivia');

-- Eventos con artistas que tienen imágenes en el frontend
-- IDs de ciudades: SCL=1, VAP=2, VDA=3 (orden de inserción)
INSERT INTO events (code, city_id, name, venue, capacity, available_tickets, artist, event_date, event_time, price, image_url, featured, status) VALUES 
('evt-braxton-001', 1, 'Braxton Cook Live', 'Teatro Nescafé de las Artes', 800, 800, 'Braxton Cook', '2026-12-15T20:00:00', '20:00', 45000.0, '/images/braxton.webp', true, 'ON_SALE'),
('evt-elena-002', 1, 'Elena Pinderhughes Quintet', 'Centro Cultural Gabriela Mistral', 600, 450, 'Elena Pinderhughes', '2027-01-20T21:00:00', '21:00', 55000.0, '/images/elena.webp', true, 'SCHEDULED'),
('evt-internet-003', 2, 'The Internet - Hive Mind Tour', 'Teatro Caupolicán', 4500, 4000, 'The Internet', '2027-03-10T20:00:00', '20:00', 65000.0, '/images/internet.jfif', true, 'SCHEDULED'),
('evt-genevieve-004', 3, 'Genevieve Artadi Solo', 'Teatro del Lago', 1000, 800, 'Genevieve Artadi', '2027-02-14T19:30:00', '19:30', 48000.0, '/images/genevieve.jfif', false, 'SCHEDULED'),
('evt-jazmin-005', 1, 'Jazmin Sullivan - Heaux Tales', 'Movistar Arena', 12000, 9000, 'Jazmin Sullivan', '2027-04-05T21:00:00', '21:00', 75000.0, '/images/jazmin.jfif', true, 'SCHEDULED'),
('evt-louis-006', 2, 'Louis Cole - Quality Over Opinion', 'Centro de Convenciones', 2000, 1700, 'Louis Cole', '2027-05-12T20:00:00', '20:00', 50000.0, '/images/louis.jpg', false, 'SCHEDULED'),
('evt-terrace-007', 3, 'Terrace Martin - Velvet Portraits', 'Teatro Municipal', 1500, 1400, 'Terrace Martin', '2027-06-21T19:00:00', '19:00', 52000.0, '/images/terrace.jpg', true, 'SCHEDULED');